version: '3'
services:
  applogistik:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - VUE_APP_SECURE=$VUE_APP_SECURE
        - VUE_APP_URL=$VUE_APP_URL
        - VUE_APP_PORT=$VUE_APP_PORT
    networks:
      - gateway
    container_name: frontend-logistik-production
    ports:
      - 8081:80
    env_file:
      - .env.production

networks:
  gateway:
    external:
      name: gateway
